version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongodb:/data/db 
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_UNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}

  db-seed:
    build: 
      context: ./
      dockerfile: ./db/Dockerfile.seed
    volumes:
      - ./db/data:/data_restore
    depends_on:
      - db
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_UNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - ATLAS_DB_URI=${ATLAS_DB_URI}
      - ATLAS_DB_UNAME=${ATLAS_DB_UNAME}
      - ATLAS_DB_PASS=${ATLAS_DB_PASS}

networks:
  app-network:
    driver: bridge