export const WHATSAPP_FLOW_ACTIONS = {
    PING: 'ping',
    INIT: 'INIT',
    DATA_EXCHANGE: 'data_exchange',
} as const

export const WHATSAPP_SCREENS = {
    GIFTING_FLOW: {
        DASHBOARD: 'DASHBOARD',
        AI_MESSAGES: 'AI_MESSAGES',
        GIFT_MESSAGES: 'GIFT_MESSAGES',
        CARD_PREVIEW: 'CARD_PREVIEW',
        GIFTING_TREES: 'GIFTING_TREES',
        RECIPIENTS_A: 'RECIPIENTS_A',
    },
    EXPENSE_FLOW: {
        EXPENSE_FORM: 'EXPENSE_FORM',
        EXPENSE_SUMMARY: 'EXPENSE_SUMMARY',
        EXPENSE_SUBMITTED: 'EXPENSE_SUBMITTED',
    },
    VISIT_FLOW: {
        SITE_VISIT_WELCOME: 'SITE_VISIT_WELCOME',
        SITE_VISIT_SELECT: 'SITE_VISIT_SELECT',
        SITE_VISIT_REGISTRANT_DETAILS: 'SITE_VISIT_REGISTRANT_DETAILS',
        SITE_VISIT_CONFIRM: 'SITE_VISIT_CONFIRM',
        SITE_VISIT_SUBMITTED: 'SITE_VISIT_SUBMITTED',
    },
    MENU_FLOW: {
        MENU_SCREEN: 'MENU_SCREEN',
    },
} as const