[build]
  base = "/"
  command = "npm install && npx turbo build --filter=front-page..."
  publish = "apps/front-page/.next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  TURBO_REMOTE_ONLY = "true"
  TURBO_FORCE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable asset optimization and caching
[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false

# Handle Next.js static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/media/*"
  to = "/_next/media/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false